# Generated by Django 4.2.3 on 2023-07-19 13:55

from django.db import migrations, models
import django.db.models.deletion
import drfdynmodels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('db_name', models.CharField(default='default', max_length=32)),
                ('managed', models.BooleanField(default=True)),
                ('db_table_name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('class_name', models.TextField()),
                ('kwargs', drfdynmodels.models.FieldKwargsJSON(default=dict)),
                ('model_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='drfdynmodels.modelschema')),
            ],
            options={
                'unique_together': {('name', 'model_schema')},
            },
        ),
    ]
